INSERT INTO
    sensors.litime (
        time,
        total_voltage,
        cell_voltage_sum,
        current,
        mosfet_temp,
        cell_temp,
        remaining_ah,
        full_capacity_ah,
        protection_state,
        heat_state,
        balance_memory,
        failure_state,
        balancing_state,
        battery_state,
        soc,
        soh,
        discharges_count,
        discharges_ah_count,
        cell_voltages
    )
VALUES
    (
        $1,
        $2,
        $3,
        $4,
        $5,
        $6,
        $7,
        $8,
        $9,
        $10,
        $11,
        $12,
        $13,
        $14,
        $15,
        $16,
        $17,
        $18,
        $19
    );